package features

import (
	"reflect"
)

// Taken from https://docs.google.com/spreadsheets/d/1CfTEmDsjnuh_flWhSFVZ6wqWR7m7egeyVD6BXppgCyE/edit#gid=1074788665

// Default global checklist.
// Helper template function for randomized testing.
var List = Checklist{}

func SumCategories(checklist interface{}) map[string]int {
	support := make(map[string]int)

	checklistValue := reflect.ValueOf(checklist)
	checklistType := checklistValue.Type()

	for i := 0; i < checklistType.NumField(); i++ {
		field := checklistType.Field(i)
		fieldValue := checklistValue.Field(i)

		if fieldValue.Kind() == reflect.Struct {
			// Nested struct, recursively process
			// Don't need a supported check, since they already have "Used"
			nestedCounts := SumCategories(fieldValue.Interface())
			for category, count := range nestedCounts {
				support[category] += count
			}
		} else {
			// Check for the "category" tag and increment count if true
			if category, ok := field.Tag.Lookup("supported"); ok && fieldValue.Bool() {
				support[category]++
			} else {
				support["unknown"]++
			}
		}
	}

	return support
}

// The feature checklist structure.
// Fields are marked with yes,no,partial for supported status
// This is used for summarizing v2 feature usage
type Checklist struct {
	// TODO: Check this with Rahul? Do we care about backends for this report?
	Sources struct {
		Used      bool `supported:"yes"`
		FromEnv   bool `supported:"yes"`
		PG        bool `supported:"yes"`
		SQLServer bool `supported:"no"`
		MySQL     bool `supported:"no"`
		Mongo     bool `supported:"no"`
	}

	Tables struct {
		Used bool `supported:"yes"`
		/* // These are actions on MD, not features:
		TrackModels bool
		TrackForeignKeys bool
		TrackFunctions bool
		*/
		CommentsOnModels bool `supported:"yes"`
		EnumTables       bool `supported:"no"` // TODO: Check
		ApolloFederation bool `supported:"no"`
	}

	Relationships struct {
		Used                               bool `supported:"yes"`
		LocalRelationshipWithForeignKey    bool `supported:"yes"`
		LocalRelationshipWithoutForeignKey bool `supported:"yes"` // TODO: Check
		RemoteRelationship                 bool `supported:"yes"`
	}

	RemoteSchemas struct {
		Used          bool `supported:"no"`
		Configuration struct {
			Used           bool `supported:"no"`
			FromEnv        bool `supported:"no"`
			Timeout        bool `supported:"no"`
			Headers        bool `supported:"no"`
			DynamicHeaders bool `supported:"no"`
		}
		Relationships struct {
			Used            bool `supported:"no"`
			ToDatabase      bool `supported:"no"`
			ToRemoteSchema  bool `supported:"no"`
			ArgumentPresets bool `supported:"no"`
		}
		Permissions bool `supported:"no"`
		BypassAuth  bool `supported:"no"`
	}

	Queries struct {
		Used bool
		// AutoGeneratedQueryFeatures bool // N/A?
		QueryList         bool `supported:"yes"` // TODO: These are implicit in V2 right?
		QueryByPrimaryKey bool `supported:"yes"`
		DistinctOn        bool `supported:"yes"`
		// It may be difficult to determine this from metadata...
		Where struct {
			Used                 bool `supported:"yes"`
			BasicUsage           bool `supported:"yes"`
			WithBoolExpression   bool `supported:"yes"`
			Operators            bool `supported:"partial"`
			AggregateExpressions bool `supported:"no"`
		}
		Pagination          bool `supported:"yes"`
		Limit               bool `supported:"yes"`
		Offset              bool `supported:"yes"`
		OrderBy             bool `supported:"yes"`
		Aggregate           bool `supported:"no"`
		SimpleObjectQueries struct {
			Used                   bool `supported:"yes"`
			ScalarIntegerAndText   bool `supported:"yes"`
			ScalarJSON             bool `supported:"no"`
			NestedObjects          bool `supported:"no"` // TODO: Check
			AggregateNestedObjects bool `supported:"no"`
		}
		BoolExpressions bool `supported:"partial"`
		Introspection   bool `supported:"yes"` // TODO: Check
		// RunSQL          bool // N/A?
		Permissions struct {
			Used              bool `supported:"yes"`
			ColumnPermisisons bool `supported:"yes"`
			PermissionRules   bool // TODO: Check?
		}
		QueryCollection bool `supported:"no"`
	}

	Mutations struct {
		Used    bool `supported:"no"`
		Simple  bool `supported:"no"`
		Complex bool `supported:"no"`
	}

	LogicalModels struct {
		Used bool `supported:"yes"`
	}

	NativeQueries struct {
		Used    bool `supported:"yes"`
		Queries struct {
			Used        bool `supported:"yes"`
			Permissions bool `supported:"yes"`
		}
		Mutations struct {
			Used        bool `supported:"yes"`
			Permissions bool `supported:"no"`
		}
	}

	Actions struct {
		Used      bool
		Queries   bool
		Mutations bool
		Types     struct {
			Used              bool
			CustomTypes       bool
			CustomScalarTypes bool
		}
		HttpConfiguration struct {
			Used                 bool
			ConfiguredEndpoints  bool
			URLTemplating        bool
			RequestMethod        bool
			StaticHeaders        bool
			DynamicHeaders       bool
			ForwardClientHeaders bool
		}
		AsyncActions bool
		/* /// Not part of configuration
		* Open API Import
			* Single Import
			* bulk import
			* error handling during import
			* support yaml & JSON
		* Code Gen
			* Support multiple programming languages & frameworks
		* Derive Actions
		*/
		BasicPermissions bool
		Relationships    struct {
			Used           bool
			ActionToDB     bool
			ActionToRS     bool
			ActionToAction bool
		}
		Transforms struct {
			Used              bool // Subsumes Kriti Feature.
			RequestTransforms struct {
				Used           bool
				ContextObjects bool
				RequestMethod  bool
				RequestURL     bool
				RequestBody    bool
			}
			ResponseTransforms struct {
				Used           bool
				ContextObjects bool
				DebuggingMode  bool
			}
			PayloadTransforms struct {
				Used                   bool
				ResponseBodyTransforms bool
			}
		}
		// * Async Action logs cleanup (?) // What's this?
	}

	EventTriggers struct {
		Used  bool
		Types struct {
			Insert bool
			Update bool
			Delete bool
			// Via console: N/A?
			ColumnSpecificUpdates bool
		}
		TriggerProtocols struct {
			Webhook bool
		}
		// * Auto Cleanup Event Logs (Make sure event logs are cleared periodically): N/A?
		RequestTransforms struct {
			UsesRequestTransforms bool
			Headers               bool
			RequestMethod         bool
			RequestURL            bool
			RequestBody           bool
			Context               bool
		}
		ResponseTransforms struct {
			UsesResponseTransforms bool
		}
		PayloadTransform struct {
			ResponseBodyTransforms bool
		}
		RetryLogicConfiguration bool
		/* // N/A?
		* Simulation
			* Event triggers can be tested by manually triggering from console
		* Codegen
		* Observability
		* Performance
		*/
	}

	Authentication struct {
		Used bool
		JWTs struct {
			UsesJWTs bool
			Secret   bool
			JWK      bool
		}
		Webhook              bool
		AdminRole            bool
		UnauthorisedAccess   bool
		MultipleAdminSecrets bool
		MultipleJWTs         bool
	}

	Authorization struct {
		Used                      bool
		RoleFromSessionVariable   bool
		RoleBasedSchemeGeneration bool
		ConfigureRowPermissions   bool
		ColumnPermissions         bool
		AggregationPermissions    bool
		RowFetchLimit             bool
		RootFieldVisibility       bool
		ColumnPresets             bool
		BackendOnlyMutations      bool
		PermissionsOperators      bool
		// PermissionsSummary (on Console): N/A?
	}

	Relay struct {
		Used    bool
		Queries struct {
			UsesQueries                 bool
			ConnectionObjectsNodesEdges bool
		}
		Subscriptions bool
		Mutations     bool
	}

	RESTifiedEndpoints struct {
		Used                     bool
		BasicGraphql             bool
		ArgumentsFromPayloadBody bool
		ArgumentsFromURLParams   bool
		DifferentHTTPMethods     bool
		// * RESTified endpoint playground (like GraphiQL UI, to test REST endpoints): N/A?
	}

	/* // Not able to be detected from metadata:
	### Caching
	* Basic Caching with @cached
	* With Custom TTL @cached(ttl: 120)
	* forcing a refresh @cached(refresh: true)
	*/

	AllowLists struct {
		Used                                    bool
		ConfigureQueryCollectionsWithRoleAccess bool
		MultipleQueryColectionsAndRoles         bool
		CachingMetrics                          bool // ??
		EnterpriseSuppport                      struct {
			UsesEnterpriseSuppport    bool
			CustomRedisConfigurations bool
		}
	}

	APILimits struct {
		Used        bool
		RateLimits  bool
		DepthLimits bool
		NodeLimits  bool
		TimeLimits  bool
		BatchLimits bool
	}

	// How to detect this?
	DynamicEnvironmentVariables struct {
		Used                         bool
		ZeroDowntimeSecretResolution bool
	}

	/* // N/A?
	### Other
	* Metadata Consistency
	* Schema Registry
	* Federation
		* Apollo Federation
	*/

	// The following may need to be detected in telemetry data:
	// --------------------------------------------------------

	Subscriptions struct {
		Used bool
	}

	Observability struct {
		Used             bool
		OpenTelemetry    bool
		MetricsURL       bool
		TracePropogation bool
		Headers          bool
		Attrubutes       bool
		APMIntegrations  struct {
			Prometheus   bool
			Datadog      bool
			NewRelic     bool
			AzureMonitor bool
		}
		QueryTags bool
	}
}
