name: Build

on:
  push:
    branches:
      - main

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: 'linux/amd64, linux/arm64, darwin/amd64, darwin/arm64, windows/amd64'
          package: ''
          name: 'upgrade-from-v2'
          compress: 'true'
          dest: 'dist'
