name: Distribution

on:
  push:
    branches:
      - main
    tags:        
      - v*

jobs:
  distribute:

    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     go-version: [ '1.19', '1.20', '1.21.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go # ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.4
        #   go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: Test
        run: make test
      - name: Build
        run: make build
      - name: Manifest
        run: make manifest
      - name: Setup-GCLoud
        run: make setup-gcloud
        env:
          UPGRADE_FROM_V2_GCLOUD_SERVICE_KEY_BASE64: ${{ secrets.UPGRADE_FROM_V2_GCLOUD_SERVICE_KEY }}
      - name: Push
        run: make push-artifacts
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.INDEX_PRIVATE_KEY }}
      - name: Update Plugins Index
        run: make plugin-index-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INDEX_PUBLIC_KEY: ${{ secrets.INDEX_PUBLIC_KEY }}
          INDEX_PRIVATE_KEY: ${{ secrets.INDEX_PRIVATE_KEY }}
        # if: startsWith(github.ref, 'refs/tags/v')

